[project]
name = "mcp-server-example"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
  "boto3",
  "fastapi",
  "fastmcp",
  "google-api-python-client",
  "google-auth-httplib2",
  "langchain-community",
  "mangum",
]
