name: hands-on-lambda-ecr-apps-hello-world
run-name: ${{ github.event_name }} on ${{ github.ref_name }} by @${{ github.actor }} inputs ${{ github.event.inputs.environment }} ${{ github.event.inputs.action }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.11.4"
  TF_WORKING_DIR: "./services/hands-on-lambda-ecr"
  TF_PLAN_FILE: "plan.tfplan"
  APP_NAME: "hello-world"

permissions:
  id-token: write
  contents: read

jobs:
  plan_apply_apps:
    name: "Plan/Apply Apps"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.HANDS_ON_LAMBDA_ECR_TERRAFORM_IAM }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Plan for Lambda
        id: tf_plan
        env:
          ENV: ${{ github.event.inputs.environment || 'dev' }}
          TF_BACKEND_S3_BUCKET: ${{ secrets.TF_BACKEND_S3_BUCKET }}
        run: |
          make lambda-plan \
            APP_NAME=${{ env.APP_NAME }} \
            LAMBDA_VAR_FILES= \
            LAMBDA_ARGS='-var=github_repository=${{ github.repository }} -var=aws_region=${{ env.AWS_REGION }}'
          ls -l lambdas/${{ env.APP_NAME }}
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply for Lambda
        if: github.event.inputs.action == 'apply'
        env:
          ENV: ${{ github.event.inputs.environment || 'dev' }}
          TF_BACKEND_S3_BUCKET: ${{ secrets.TF_BACKEND_S3_BUCKET }}
        run: |
          ls -l lambdas/${{ env.APP_NAME }}
          make lambda-apply APP_NAME=${{ env.APP_NAME }}
        working-directory: ${{ env.TF_WORKING_DIR }}
