name: hands-on-lambda-ecr-deploy
run-name: ${{ github.event_name }} on ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: "ap-northeast-1"
  ECR_REPOSITORY_BASE_NAME: "hands-on-lambda-ecr" # Base name, env suffix will be added
  LAMBDA_FUNCTION_BASE_NAME: "hello-world-python-container" # Base name, env suffix will be added
  TF_VERSION: "1.11.4" # Terraformのバージョンを固定 (例: "1.8.4")

permissions:
  id-token: write
  contents: read

jobs:
  deploy_infrastructure: # Renamed from deploy_lambda, and provision_ecr_and_iam is removed
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    # 'needs' clause removed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.HANDS_ON_LAMBDA_ECR_ARN_IAM_OIDC }} # User might need to make this env-specific
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr # This step is crucial for getting the ECR registry
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: make tf-init ENVIRONMENT=${{ github.event.inputs.environment }}
        working-directory: ./services/hands-on-lambda-ecr # Makefile is in this directory

      - name: Terraform Validate
        run: make tf-validate ENVIRONMENT=${{ github.event.inputs.environment }}
        working-directory: ./services/hands-on-lambda-ecr # Makefile is in this directory

      - name: Terraform Plan
        env:
          # Define environment-specific names for constructing TF_OPT
          CURRENT_ECR_REPOSITORY_NAME: ${{ env.ECR_REPOSITORY_BASE_NAME }}-${{ github.event.inputs.environment }}
          CURRENT_LAMBDA_FUNCTION_NAME: ${{ env.LAMBDA_FUNCTION_BASE_NAME }}-${{ github.event.inputs.environment }}
        run: |
          TF_OPT_VARS="-var='ecr_image_uri=${{ steps.login-ecr.outputs.registry }}/${{ env.CURRENT_ECR_REPOSITORY_NAME }}:${{ github.sha }}' \
                       -var='ecr_repository_name=${{ env.CURRENT_ECR_REPOSITORY_NAME }}' \
                       -var='lambda_function_name=${{ env.CURRENT_LAMBDA_FUNCTION_NAME }}'"
          make plan ENVIRONMENT=${{ github.event.inputs.environment }} TF_OPT="${TF_OPT_VARS}"
        working-directory: ./services/hands-on-lambda-ecr # Makefile is in this directory

      - name: Terraform Apply
        run: make apply ENVIRONMENT=${{ github.event.inputs.environment }}
        working-directory: ./services/hands-on-lambda-ecr # Makefile is in this directory
